name: Update Request CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-request:
    runs-on: native

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Update flake.lock
        run: |
          git config --global user.name "Kolyma's Labor"
          git config --global user.email "support@kolyma.uz"
          nix flake update --commit-lock-file --accept-flake-config

      - name: Push changes
        run: |
          git config --global user.name "Kolyma's Labor"
          git config --global user.email "support@kolyma.uz"
          git remote rm origin
          git remote add origin "https://kolyma-labor:$TOKEN@git.floss.uz/orzklv/nix.git"
          git push --set-upstream origin master
        env:
          TOKEN: ${{ secrets.PAT }}
